name: minimal-db

services:
  db:
    container_name: minimal-pg
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    volumes:
      - ./pgdata-minimal:/var/lib/postgresql/data
    ports:
      - 5432:5432
